# - name: "update apt packages"
  # apt:
    # update_cache: yes

# - name: "upgrade packages"
  # become: yes
  # apt:
    # upgrade: yes
    
- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
      
    # Use n version manager to switch to Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0
    
    
- name: "add env variables"
  shell: |
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_HOST=database-2.cnskowxsuv5q.us-east-1.rds.amazonaws.com
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=mypassword
    export TYPEORM_DATABASE=postgres
    export TYPEORM_MIGRATIONS=./migrations/*.ts
    export TYPEORM_MIGRATIONS_DIR=./src/migrations


- name: Install pm2 globally
  npm:
    name: pm2
    global: yes