- name: List directory contents
  shell: ls -l
  register: ls_result

- name: Display result
  debug:
    var: ls_result.stdout_lines

- name: Extract artifact.tar.gz
  become: yes
  unarchive:
    src: /artifact.tar.gz
    dest: /

- name: Install npm packages
  command: npm install

- name: Start the application using PM2
  command: pm2 start npm -- start